- Infra:
    - PVE:
        icon: {{HOMEPAGE_VAR_PROXMOX_ICON}}
        href: https://pve.d3adc3ii.cc 
        ping: 10.10.10.10
        widget:
            type: proxmox
            url:  https://10.10.10.10:8006
            username: homepage@pve!homepage 
            password: {{HOMEPAGE_VAR_PROXMOX_SECRET}}       
            node: pve10
    - Ceph:
        icon: sh-ceph-light 
        href: https://ceph.d3adc3ii.cc
    -  Truenas:
        id: truenas 
        icon: {{HOMEPAGE_VAR_TRUENAS_ICON}}
        href: {{HOMEPAGE_VAR_TRUENAS_URL}}
        sitemonitor: {{HOMEPAGE_VAR_TRUENAS_URL}}
        widget:
            type: truenas
            url: https://truenas.d3adc3ii.cc
            key: {{HOMEPAGE_VAR_TRUENAS_KEY}}
            enablePools: {{HOMEPAGE_VAR_TRUENAS_ENABLEDPOOL}}
            nasType: scale
    - Komodo:
        icon: {{HOMEPAGE_VAR_KOMODO_ICON}} 
        href: {{HOMEPAGE_VAR_KOMODO_URL}}
        sitemonitor: {{HOMEPAGE_VAR_KOMODO_URL}}
        widget:
            type: komodo
            url: {{HOMEPAGE_VAR_KOMODO_IPURL}}
            key: {{HOMEPAGE_VAR_KOMODO_KEY}}
            secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
            showSummary: true # optional, default: false
            showStacks: true # optional, default: false
